
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class TelaInicial extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement p;
    private ResultSet r;
  
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
            if (con == null)
            con = new ConexaoBD().getConnection();
           
            iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoFechar = new javax.swing.JButton();
        botaoInserir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        campoCodigo = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoEnd = new javax.swing.JTextField();
        botaoPrim = new javax.swing.JButton();
        botaoAnt = new javax.swing.JButton();
        botaoProx = new javax.swing.JButton();
        botaoUlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        jLabel1.setText("Código");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Nome:", "Endereço:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        botaoPrim.setText("|<");
        botaoPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrimActionPerformed(evt);
            }
        });

        botaoAnt.setText("<<");
        botaoAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAntActionPerformed(evt);
            }
        });

        botaoProx.setText(">>");
        botaoProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProxActionPerformed(evt);
            }
        });

        botaoUlt.setText(">|");
        botaoUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(campoEnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoExcluir)
                            .addComponent(botaoEditar)
                            .addComponent(botaoInserir)
                            .addComponent(botaoFechar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoPrim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoProx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoUlt)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoInserir)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoFechar))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPrim)
                    .addComponent(botaoAnt)
                    .addComponent(botaoProx)
                    .addComponent(botaoUlt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar(){
           try {
            // TODO add your handling code here:
            Statement st = con.createStatement(); 
            r = st.executeQuery("SELECT CODIGOA, NOMEA, ENDERECOA FROM ALUNO");
            String conteudo[] = new String[3];
            
            DefaultTableModel dm = new DefaultTableModel(); 
            dm.addColumn("Codigo:");
            dm.addColumn("Nome:");
            dm.addColumn("Endereço:");
            if(r.next()){                
                conteudo[0] = r.getString("CODIGOA");
                conteudo[1] = r.getString("NOMEA");
                conteudo[2] = r.getString("ENDERECOA");
                dm.addRow(conteudo); 
            campoCodigo.setText(r.getString("CODIGOA"));
            campoNome.setText(r.getString("NOMEA"));
            campoEnd.setText(r.getString("ENDERECOA"));
            
                
            }
            
            while(r.next()){                
                conteudo[0] = r.getString("CODIGOA");
                conteudo[1] = r.getString("NOMEA");
                conteudo[2] = r.getString("ENDERECOA");
                dm.addRow(conteudo);                
            }
            jTable1.setModel(dm);
            
        
            
            
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        excluirAluno();
        iniciar();
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void botaoPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrimActionPerformed
        // TODO add your handling code here:
                try {
            if (r != null) {
                if (r.first()) {
                    campoCodigo.setText(r.getInt("CODIGOA")+"");
                    campoNome.setText(r.getString("NOMEA"));
                    campoEnd.setText(r.getString("ENDERECOA"));
                    
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
     
    }//GEN-LAST:event_botaoPrimActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // TODO add your handling code here:
        editarAluno();
        iniciar();
        
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void limparTabela(){
    
    
    
    
    }
    
    private void botaoAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAntActionPerformed
        // TODO add your handling code here:

try {
            if (r != null) {
                if (r.relative(-1)) {
                    campoCodigo.setText(r.getInt("CODIGOA")+"");
                    campoNome.setText(r.getString("NOMEA"));
                    campoEnd.setText(r.getString("ENDERECOA"));
                    
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
     
    }//GEN-LAST:event_botaoAntActionPerformed

    private void botaoProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProxActionPerformed
        // TODO add your handling code here:
try {
            if (r != null) {
                if (r.next()) {
                    campoCodigo.setText(r.getInt("CODIGOA")+"");
                    campoNome.setText(r.getString("NOMEA"));
                    campoEnd.setText(r.getString("ENDERECOA"));
                    
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
     
    
    }//GEN-LAST:event_botaoProxActionPerformed

    private void botaoUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUltActionPerformed
        // TODO add your handling code here:
try {
            if (r != null) {
                if (r.last()) {
                    campoCodigo.setText(r.getInt("CODIGOA")+"");
                    campoNome.setText(r.getString("NOMEA"));
                    campoEnd.setText(r.getString("ENDERECOA"));
                    
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_botaoUltActionPerformed

  
 private void adicionarAluno() {
        
        String sql;
        
        try {
            
            if (con == null)
                con = new ConexaoBD().getConnection();
           
            
            
            
             sql = "INSERT INTO ALUNO (CODIGOA, NOMEA, ENDERECOA) "
                    + "VALUES (?, ?, ?)";
            
            p = con.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(campoCodigo.getText()));
            p.setString(2, campoNome.getText());
            p.setString(3, campoEnd.getText());           
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        } finally {
            try {
                p.close();
                r.close();
            } catch (SQLException e) {
                System.out.println("Erro: "+e);
            }
        }
        
    }
    
   private void editarAluno() {
        String sql = "UPDATE ALUNO SET "
                    + "NOMEA = ?, "
                    + "ENDERECOA = ? "
                    + "WHERE CODIGOA = ?";
        
        
        try {
            
            if (con == null)
                con = new ConexaoBD().getConnection();
            
            p = con.prepareStatement(sql);
            p.setInt(3, Integer.valueOf(campoCodigo.getText()));
            p.setString(1, campoNome.getText());
            p.setString(2, campoEnd.getText());
            
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    
    }
    
   private void excluirAluno() {
        String sql = "DELETE FROM ALUNO "
                    + "WHERE CODIGOA = ?";
        
        try {
            
            if (con == null)
                con = new ConexaoBD().getConnection();
            
            p = con.prepareStatement(sql);
            p.setInt(1, Integer.valueOf(campoCodigo.getText()));
            
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
        
    }
    
    
    
    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        // TODO add your handling code here:  
            adicionarAluno();
            iniciar();
       
    }//GEN-LAST:event_botaoInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAnt;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JButton botaoPrim;
    private javax.swing.JButton botaoProx;
    private javax.swing.JButton botaoUlt;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoEnd;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
